services:
  orangehrm:
    image: orangehrm/orangehrm:5.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - orangehrm-data:/var/www/html
      - orangehrm-cert-data:/etc/letsencrypt
    networks:
      - orangehrm
    container_name: orangehrm

  mariadb1011:
    image: mariadb:10.11.4
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PW}
    volumes:
      - orangehrm-db-data:/var/lib/mysql
    networks:
      - orangehrm
    container_name: mariadb

networks:
  orangehrm:

volumes:
  orangehrm-data:
  orangehrm-cert-data:
  orangehrm-db-data:
