services:
  orangehrm:
    image: orangehrm/orangehrm:5.5
    restart: always
    ports:
      - "80:80"
    networks:
      - orangehrm
    container_name: orangehrm

  mariadb1011:
    image: mariadb:10.11.4
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PW}
    volumes:
      - orangehrm-data:/var/lib/mysql
    networks:
      - orangehrm
    container_name: mariadb

networks:
  orangehrm:

volumes:
  orangehrm-data:
