#!/bin/bash

export OHRM_DIR=/home/ec2-user/.orangehrm
export SCRIPT_DIR="${OHRM_DIR}/scripts"
export HELPER_DIR="${SCRIPT_DIR}/helper"
export ASSET_DIR="${OHRM_DIR}/assets"
export LOG_DIR="${OHRM_DIR}/logs"

export RED="\e[1;31m"
export GREEN="\e[1;32m"
export YELLOW="\e[1;33m"
export ENDCOLOR="\e[0m"
export WIP_ICON="🚧"
export SUCCESS_ICON="✅"
export ERROR_ICON="🔴"

export YES_REGEX="^y(e|es)?$"
export NO_REGEX="^n(o)?$"

check_installed() {
    if ! [[ -f "${OHRM_DIR}/.installed" ]]; then
        ohrm_script status
        exit 1
    fi
}

# Function to run scripts.
# Give the name of the script as the first argument
# Give "check" as the second argument if the install status needs to be checked
ohrm_script() {
    if [[ $2 = "check" ]]; then
        check_installed
    fi
    sh "${SCRIPT_DIR}/${1}"
}

cleanup() {
    unset OHRM_DIR
    unset SCRIPT_DIR
    unset ASSET_DIR
    unset RED
    unset GREEN
    unset YELLOW
    unset ENDCOLOR
    unset WIP_ICON
    unset SUCCESS_ICON
    unset ERROR_ICON
    unset YES_REGEX
    unset NO_REGEX
}

# shellcheck disable=SC2317
err_exit() {
    echo -e "\n${RED}Something has gone wrong!${ENDCOLOR}"
    cp -r "${LOG_DIR}" "${HOME}/orangehrm_command_logs"
    echo -e "Please find the relevant logs files at ${GREEN}${HOME}/orangehrm_command_logs\n${ENDCOLOR}"
    cleanup
    exit 1
}

# shellcheck disable=SC2317
install_err_exit() {
    echo -e "\n${RED}Something has gone wrong!${ENDCOLOR}"
    cp -rf "${LOG_DIR}" "${HOME}"
    echo -e "Please find the relevant logs files at ${GREEN}${HOME}/logs\n${ENDCOLOR}"
    echo -e "Please run ${GREEN}orangehrm clean${ENDCOLOR} and try installing again"
    cleanup
    exit 1
}

trap err_exit ERR

# Create log dir
if ! [[ -d "${LOG_DIR}" ]]; then
    mkdir -p "${LOG_DIR}"
fi

if [[ $# -eq 0 ]]; then
    # If no arguments
    help
else
    case $1 in
        install)
            trap install_err_exit ERR
            ohrm_script install
            ;;
        update)
            ohrm_script update check
            ;;
        backup)
            ohrm_script backup check
            ;;
        restore)
            # Add option to disable check
            ohrm_script restore check
            ;;
        clean)
            ohrm_script clean
            ;;
        status)
            ohrm_script status
            ;;
        check-update)
            ohrm_script check_update check
            ;;
        get-logs)
            ohrm_script get_logs check
            ;;
        help)
            ohrm_script help
            ;;
        *)
            echo -e "\n${RED}${1}${ENDCOLOR} is not an orangehrm command"
            echo -e "See '${GREEN}orangehrm help${ENDCOLOR}'\n" 
            ;;
    esac
fi

cleanup
exit 0;
