#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_backup_list.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run this script from the OrangeHRM command\n" >&3
    printf "i.e. orangehrm backup list\n\n" >&3
    exit 1;
fi

# Check if any backups are available
if [[ ! -d "${OHRM_DIR}/backups" || -z "$(ls -A "${OHRM_DIR}/backups")" ]]; then
    printf "You have not created any backups!\n\n" >&3
    exit 0
fi

printf "\nA list of your existing backups is given below:\n\n" >&3

backups=("${OHRM_DIR}/backups"/*)

printf "=========================================\n" >&3
printf "No.\tVer.\tDate\t\tTime\n" >&3
printf "=========================================\n" >&3
# List Backups
for index in "${!backups[@]}"; do
    # shellcheck disable=SC1091
    source "${backups[index]}/.metadata"
    printf "%d\t%s\t%s\t%s\n" "$((index+1))" "$BACKUP_VERSION" "$DATE_OF_BACKUP" "$TIME_OF_BACKUP" >&3
    printf "=========================================\n" >&3
done

printf "\nTo restore one of these backups, please run '%borangehrm backup restore%b'\n\n" "$GREEN" "$ENDCOLOR" >&3