#!/bin/bash

tput bold

echo -e "\n"

echo "                     ****."
echo "              ***********"
echo "             ***, *****,"
echo "            *  ******,"
echo "                .(."

echo "    (((((((((       ((((."
echo "  ((((        ((       (((*"
echo " (((                    (((*"
echo "((((                    (((("
echo " ((((                   (((("
echo " *(((((               /(((("
echo "   (((((((/        ((((((("
echo "     ,((((((((((((((((("
echo "          ((((((((("

echo -e "\n"

tput sgr0
