#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_check_update.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run this script from the OrangeHRM command\n" >&3
    printf "i.e. orangehrm backup\n\n" >&3
    exit 1;
fi

# Function to run backup scripts.
# Give the name of the script as the first argument
ohrm_backup_script() {
    sh "$BACKUP_SCRIPTS_DIR/$1" >&3
}

if [[ $# -eq 0 ]]; then
    # If no arguments
    ohrm_backup_script backup_help
else
    case $1 in
        help)
            ohrm_backup_script backup_help
            ;;
        create)
            ohrm_backup_script create
            ;;
        restore)
            ohrm_backup_script restore
            ;;
        list)
            ohrm_backup_script list
            ;;
        clean)
            ohrm_backup_script clean
            ;;
        *)
            printf "\n%b%s%b is not an orangehrm backup commmand" "$RC" "$1" "$EC" >&3
            printf "See '%borangehrm backup help%b'\n\n" "$GC" "$EC" >&3
            ;;
    esac
fi
