#!/bin/bash

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run the script from the OrangeHRM command\n\n"
    exit 1;
fi

# shellcheck disable=SC1091
source "${OHRM_DIR}/.installed"

newVersion=$(curl --silent https://raw.githubusercontent.com/devishke-orange/orangehrm-aws/main/compose.yml | grep "    image: orangehrm/orangehrm:" | sed 's/    image: orangehrm\/orangehrm://')

if [[ "${OHRM_VERSION}" = "${newVersion}" ]]; then
    echo -e "\n${GREEN}OrangeHRM is up to date!${ENDCOLOR}\n"
else
    echo -e "\nA new version of OrangeHRM is available!"
    echo -e "Please run '${GREEN}orangehrm update${ENDCOLOR}' to upgrade!\n"
fi

exit 0;
