#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_clean.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    ohrm_print "\nPlease run this script from the OrangeHRM command\n"
    ohrm_print "i.e. orangehrm clean\n\n"
    exit 1;
fi

answer="no"

printf "\n%bWARNING%b: You are about to completely remove all data and backups related to your installation of OrangeHRM!\n\n" "$RC" "$EC" >&3
printf "Are you sure you want to continue? [%byes/no%b]\n" "$YC" "$EC" >&3

read -rp "> " answer 2>&3

while ! yes_no_check "$answer"; do
    printf "Please enter yes or no\n" >&3
    read -rp "> " answer 2>&3
done

quit_if_input "$NO_REGEX" "$answer" "\nCleaning process aborted!\n\n"

ohrm_print "\n"

print_progress_message "Wiping OrangeHRM data" wip

docker compose -f "$COMPOSE_FILE" down
docker system prune -af
if docker volume inspect orangehrm_orangehrm-data; then
    docker volume rm orangehrm_orangehrm-data
fi

print_progress_message "Wiping OrangeHRM data" success rewrite

check_file_exists_and_remove() {
    if [[ -f "$1" ]]; then
     rm -f "$1"
    fi
}

print_progress_message "Removing OrangeHRM files" wip
check_file_exists_and_remove "$COMPOSE_FILE"
check_file_exists_and_remove "$ENV_FILE"
check_file_exists_and_remove "$INSTALL_FILE"

# Not necessary to check for these since they get created when running orangehrm command
rm -rf "$BACKUP_DIR"
cp -r "$LOG_DIR" "$HOME/ohrm_logs_$(date +"%Y_%m_%d")"
rm -rf "$LOG_DIR"
print_progress_message "Removing OrangeHRM files" success rewrite

ohrm_print "\n"

ohrm_print "All data related to orangehrm has been wiped!\n\n"
printf "Your log files have been stored at %s\n" "$HOME/ohrm_logs_$(date +"%Y_%m_%d_%H_%M_%S")" >&3
printf "To reinstall the system please run '%borangehrm install%b'\n\n" "$GC" "$EC" >&3

if [[ -d "$SSL_DIR" ]]; then
    printf "If you have generated any SSL certificates, they are available in %s\n" "$SSL_DIR" >&3
    printf "You can run %borangehrm ssl restore%b after installing if you wish to reuse them\n\n" "$GC" "$EC" >&3
fi

exit 0
