#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_clean.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run this script from the OrangeHRM command\n" >&3
    printf "i.e. orangehrm clean\n\n" >&3
    exit 1;
fi

answer="no"

printf "\n%bWARNING%b: You are about to completely remove all data and backups related to your installation of OrangeHRM!\n\n" "$RC" "$EC" >&3
printf "Are you sure you want to continue? [%byes/no%b]\n" "$YC" "$EC" >&3

read -rp "> " answer 2>&3

while ! yes_no_check "$answer"; do
    printf "Please enter yes or no\n" >&3
    read -rp "> " answer 2>&3
done

quit_if_input "$NO_REGEX" "$answer" "\nCleaning process aborted!\n\n"

printf "\n" >&3

print_progress_message "Wiping OrangeHRM data" wip

docker compose --file ".orangehrm/compose.yml" down
docker system prune --all --force
if docker volume inspect orangehrm_orangehrm-data; then
    docker volume rm orangehrm_orangehrm-data
fi

rm --force "${OHRM_DIR}/.installed"
print_progress_message "Wiping OrangeHRM data" success rewrite

print_progress_message "Removing backups" wip
rm --recursive --force "${OHRM_DIR}/backups/*"
print_progress_message "Removing backups" success rewrite


printf "\nAll data related to orangehrm has been wiped!\n\n" >&3
printf "To reinstall the system please run '%borangehrm install%b'\n\n" "$GC" "$EC" >&3
exit 0
