#!/bin/bash

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run the script from the OrangeHRM command\n\n"
    exit 1;
fi

installFile="${OHRM_DIR}/.installed"

if [[ -f "${installFile}" ]]
then
    # shellcheck disable=SC1090,SC1091
    source "${installFile}"
    echo -e "\n${GREEN}OrangeHRM ${OHRM_VERSION} is installed!${ENDCOLOR}\n"
else
    echo -e "\n${YELLOW}OrangeHRM is not installed!${ENDCOLOR}"
    echo -e "Run '${GREEN}orangehrm install${ENDCOLOR}' to start the installation\n"
fi
