#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_ssl_add_domain.log" 2>&1
set -x
set -e

if [[ -z $OHRM_DIR ]]; then
    printf "\nPlease run this script from the OrangeHRM command\n" >&3
    printf "i.e. orangehrm ssl\n\n" >&3
    exit 1;
fi

ohrm_print "This tool assists you with adding new domains to your server configuration after SSL certificate generation\n"

print_progress_message "Checking for existing certificates" wip

if docker run -it --rm --name certbot --mount source=orangehrm_orangehrm-cert,target=/etc/letsencrypt certbot/certbot certificates | grep "No certificates found"; then
    ohrm_print "You have not generated any certificates\n"
    printf "You can run '%borangehrm ssl enable%b'\n\n" "$GC" "$EC" >&3
    exit 0
fi

print_progress_message "Checking for existing certificates" success rewrite

ohrm_print "Your available certificates:\n"

docker run -it --rm --name certbot --mount source=orangehrm_orangehrm-cert,target=/etc/letsencrypt certbot/certbot certificates >&3

ohrm_print "Your enabled sites:\n"

docker exec orangehrm ls /etc/apache2/sites-enabled | sed 's/.conf//g' >&3

domain_name=""

read -rp "Add a new domain to be enabled (it should match the name in the certificate list exactly):\n> " domain_name
if ! docker exec orangherm ls /etc/apache2/sites-enabled | grep "^$domain_name"; then
    if docker run -it --rm --name certbot --mount source=orangehrm_orangehrm-cert,target=/etc/letsencrypt certbot/certbot certificates | grep "^$domain_name$"; then
        docker cp "$SSL_CONF_FILE" "orangehrm:/etc/apache2/sites-available/$domain_name.conf"
        docker exec orangehrm sed -i "s/YOUR_SERVER_NAME/$domain_name/g" "/etc/apache2/sites-available/$domain_name.conf"
        docker exec orangehrm ln -s "../sites-available/$domain_name.conf" "/etc/apache2/sites-enabled/$domain_name.conf"
        if docker exec orangehrm service apache2 restart; then
            ohrm_print "The apache service did not restart properly!\n"
            ohrm_print "Please run 'docker exec orangehrm service apache2 restart'\n"
        fi
    else
        ohrm_print "This site is not listed in your generated certificates!\n"
    fi
else
    ohrm_print "This site has already been enabled!\n"
fi
