#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_ssl_configure_auto_renew.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    ohrm_print "\nPlease run this script from the OrangeHRM command\n"
    ohrm_print "i.e. orangehrm ssl enable\n\n"
    exit 1
fi

ohrm_print "This tool will create a systemd timer to renew your generated SSL certificates\n"
ohrm_print "The timer will run daily at 00:00:00 UTC\n"

print_progress_message "Checking pre-requisites" wip

if docker exec certbot certbot certificates | grep "No certificates found"; then
    print_progress_message "Checking pre-requisites" error rewrite
    ohrm_print "You have not generated any certificates!\n"
    printf "You can run %borangehrm%b ssl enable to get started\n\n" "$GC" "$EC" >&3
    exit 1
fi

if [[ $UID -ne 0 ]]; then
    print_progress_message "Checking pre-requisites" error rewrite
    ohrm_print "Please run this script with superuser privileges\n"
    ohrm_print "i.e. sudo orangehrm ssl configure_auto_renew\n\n"
    exit 1
fi

print_progress_message "Checking pre-requisites" success rewrite

print_progress_message "Setting up auto renewal" wip

cp -f "SSL_RENEW_SERVICE" /etc/systemd/system
cp -f "SSL_RENEW_TIMER" /etc/systemd/system

systemctl start ssl_renew.timer
systemctl enable ssl_renew.timer

if systemd-analyze verify /etc/systemd/system/ssl_renew*; then
    print_progress_message "Setting up auto renewal" success rewrite
    ohrm_print "SSL Auto Renewal has been configured successfully!\n\n"
else
    print_progress_message "Setting up auto renewal" error rewrite
    ohrm_print "Something has gone wrong with the timers!\n"
    ohrm_print "Please run 'systemd-analyze verify /etc/systemd/system/ssl_renew*' to check the error\n\n"
fi