#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_ssl_enable.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run this script from the OrangeHRM command\n" >&3
    printf "i.e. orangehrm ssl enable\n\n" >&3
    exit 1;
fi

printf "This script will run certbot from EFF\n"
printf "Elaborate on process here!\n\n"

read -rp "Press ENTER to to continue"

printf "\nPlease provide the following information in order to generate your SSL certificate from Let's Encrypt\n"

# Required variables
domain_name=""
email=""
agree_eff=""
agree_mail=""
