name: RPM Build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install docker
        run: sudo apt-get install docker -y

      - name: Create build dir
        run: mkdir build

      - name: Setup Amazon Linux container
        run: |
          docker run -dit --name AWS --mount type=bind,source="$(pwd)"/build/,target=/home/ amazonlinux:latest
          docker exec AWS dnf install gcc rpm-build rpm-devel rpmlint make python bash diffutils patch rpmdevtools -y
          docker exec AWS adduser ec2-user
          docker exec --user ec2-user AWS rpmdev-setuptree

      - name: Copy files to rpmbuild
        run: |
          mkdir -p build/orangehrm-0.0.1
          cp compose.yml build/orangehrm-0.0.1
          cp orangehrm build/orangehrm-0.0.1
          cp -r assets build/orangehrm-0.0.1
          cp -r scripts build/orangehrm-0.0.1
          pushd build
          tar -cf orangehrm-0.0.1.tar.gz orangehrm-0.0.1
          popd
          sudo mv build/orangehrm-0.0.1.tar.gz build/ec2-user/rpmbuild/SOURCES
          sudo mv orangehrm.spec build/ec2-user/rpmbuild/SPECS
        
      - name: Lint spec file
        run: docker exec --user ec2-user AWS rpmlint /home/ec2-user/rpmbuild/SPECS/orangehrm.spec

      - name: Create rpm package
        run: docker exec --user ec2-user AWS rpmbuild -ba /home/ec2-user/rpmbuild/SPECS/orangehrm.spec
  
      # - name: Lint RPM package
      #   run: docker exec --user ec2-user AWS rpmlint /home/ec2-user/rpmbuild/RPMS/noarch/$(ls /home/ec2-user/rpmbuild/RPMS/noarch)

      - name: Copy noarch folder to base dir
        run: sudo cp -r build/ec2-user/rpmbuild/RPMS/noarch .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binary-rpm
          path: ./noarch/*.rpm
