name: RPM Build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install docker
        run: sudo apt-get install docker -y

      - name: Create build dir
        run: mkdir build

      - name: Setup Amazon Linux container
        run: |
          docker run -dit --name AWS --mount type=bind,source="$(pwd)"/build/,target=/home/ amazonlinux:latest
          docker exec AWS dnf install gcc rpm-build rpm-devel rpmlint make python bash diffutils patch rpmdevtools -y
          docker exec AWS adduser ec2-user
          docker exec --user ec2-user AWS rpmdev-setuptree

      - name: Copy files to rpmbuild
        run: |
          mkdir -p build/orangehrm-0.0.1
          cp compose.yml build/orangehrm-0.0.1
          cp oranghrm build/orangehrm-0.0.1
          cp -r assets build/orangehrm-0.0.1
          cp -r scripts build/orangehrm-0.0.1
          pushd build
          tar -cf orangehrm-0.0.1.tar.gz orangehrm-0.0.1
          popd
          ls build